// Generated by scripts/build.mjs. Do not edit.
// Basenames available as .webp in the build output.
export const webAssets=new Set(["brand-label","graphic-cafe-front","graphic-paper-front","graphic-sigil-back","graphic-sigil-front","graphic-talk-back","graphic-talk-front","studio-editorial","tee-back","tee-charcoal","tee-cream","tee-detail","tee-front","tee-orange"]);
