import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const customers=sqliteTable('customers',{id:text('id').primaryKey(),email:text('email').notNull(),name:text('name').notNull(),phone:text('phone').notNull().default(''),address:text('address').notNull().default(''),city:text('city').notNull().default(''),postcode:text('postcode').notNull().default(''),wishlist:text('wishlist').notNull().default('[]'),role:text('role').notNull().default('customer'),createdAt:text('created_at').notNull()});
export const products=sqliteTable('products',{id:text('id').primaryKey(),slug:text('slug').notNull().default(''),seoTitle:text('seo_title').notNull().default(''),seoDescription:text('seo_description').notNull().default(''),name:text('name').notNull(),color:text('color').notNull(),description:text('description').notNull(),category:text('category').notNull(),price:integer('price'),stock:integer('stock').notNull().default(0),sizes:text('sizes').notNull(),image:text('image').notNull(),back:text('back').notNull().default(''),status:text('status').notNull().default('draft'),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()});
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),customerId:text('customer_id').notNull().references(()=>customers.id),items:text('items').notNull(),subtotal:integer('subtotal'),discount:integer('discount').notNull().default(0),promoCode:text('promo_code').notNull().default(''),total:integer('total').notNull(),status:text('status').notNull(),payment:text('payment').notNull().default('pending'),address:text('address').notNull(),phone:text('phone').notNull(),trackingNumber:text('tracking_number').notNull().default(''),carrier:text('carrier').notNull().default(''),deliveryDate:text('delivery_date').notNull().default(''),note:text('note').notNull().default(''),requestKey:text('request_key').notNull(),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('idx_orders_customer_created').on(t.customerId,t.createdAt),index('idx_orders_status').on(t.status),uniqueIndex('idx_orders_request').on(t.customerId,t.requestKey)]);
export const events=sqliteTable('order_events',{id:text('id').primaryKey(),orderId:text('order_id').notNull().references(()=>orders.id),status:text('status').notNull(),message:text('message').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_events_order_created').on(t.orderId,t.createdAt)]);
export const activity=sqliteTable('activity',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),target:text('target').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_activity_created').on(t.createdAt)]);

export const promotions=sqliteTable('promotions',{id:text('id').primaryKey(),code:text('code').notNull().unique(),kind:text('kind').notNull(),value:integer('value').notNull(),minimum:integer('minimum').notNull().default(0),usageLimit:integer('usage_limit'),used:integer('used').notNull().default(0),starts:text('starts').notNull().default(''),ends:text('ends').notNull().default(''),active:integer('active').notNull().default(0),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()});
export const shopSettings=sqliteTable('shop_settings',{id:text('id').primaryKey(),value:text('value').notNull(),version:integer('version').notNull().default(1),updatedAt:text('updated_at').notNull()});
