import {renderAccounts} from './render-accounts.mjs';
import {renderStudio} from './render-studio.mjs';
import {renderCollection} from './render-collection.mjs';
import {renderCustom} from './render-custom.mjs';
import {products} from '../public/catalog.js';
import {readFile,access,mkdir,copyFile,cp,rm,readdir,writeFile} from 'node:fs/promises';
// Load .env so `npm run build` stamps the real SITE_ORIGIN into canonicals and
// structured data without needing a flag. Values already in the environment win.
try{process.loadEnvFile('.env');}catch{/* no .env: the fallback origin is used */}
await mkdir('public/vendor',{recursive:true});
for(const name of ['three.module.js','three.core.js'])await copyFile('node_modules/three/build/'+name,'public/vendor/'+name);
await renderCollection();
await renderStudio();
await renderAccounts();
await renderCustom();
await copyFile('server/domain.mjs','public/commerce.js');
await copyFile('public/catalog.js','server/catalog.js');
// The product pages are rendered in the Worker, which cannot read public/ at
// request time. Extract the shared chrome -- SVG filters, account menu, and the
// menu/bag/product dialogs -- into a module the Worker can import, so those
// pages carry byte-identical markup to the pages generated at build time.
{
 const home=await readFile('public/index.html','utf8');
 const slice=(from,to)=>home.slice(home.indexOf(from),home.indexOf(to)+to.length);
 const filters=home.slice(home.indexOf('<svg class="filter-defs"'),home.indexOf('<a class="skip-link"')).replace(/<svg class="home-doodles"[\s\S]*?<\/svg>\s*/,'');
 const accountMenu=slice('<!-- account:start -->','<!-- account:end -->');
 const siteNav=slice('<!-- nav:start -->','<!-- nav:end -->');
 const dialogs=home.slice(home.indexOf('<dialog id="menu-dialog"'),home.indexOf('</body>')).replaceAll('href="#home"','href="/"').replaceAll('href="#story"','href="/#story"').replaceAll('href="#details"','href="/#details"');
 for(const [name,value] of Object.entries({filters,accountMenu,dialogs,siteNav}))if(!value)throw new Error(`build: could not extract ${name} from public/index.html`);
 await writeFile('server/shell.js',`// Generated by scripts/build.mjs from public/index.html. Do not edit.\nexport const filters=${JSON.stringify(filters)};\nexport const accountMenu=${JSON.stringify(accountMenu)};\nexport const dialogs=${JSON.stringify(dialogs)};\nexport const siteNav=${JSON.stringify(siteNav)};\n`);
}
const html=(await readFile('public/index.html','utf8'))+(await readFile('public/collection/index.html','utf8'))+(await readFile('public/studio/index.html','utf8'));
const files=[...html.matchAll(/(?:src|href)="(\/(?:assets|vendor)\/[^"#?]+)"/g)].map(m=>m[1]);
for(const file of new Set([...files,'/films.js','/studio.css','/studio.js','/style-guide.js','/style.css','/app.js','/home.css','/home.js','/product-scene.js','/assets/tee-front.png','/assets/tee-back.png','/assets/tee-detail.png','/catalog.js','/collection.css','/collection.js','/transitions.js','/transitions.css',...products.map(p=>p.image)]))await access('public'+file);
await rm('dist',{recursive:true,force:true});
await cp('public','dist/client',{recursive:true});
await cp('server','dist/server',{recursive:true});
await copyFile('server/worker.mjs','dist/server/index.js');
// Ship the Postgres migrations with the build. Row-level security lives in
// 0002 and is the only thing standing between the public publishable key and
// every customer record, so the deploy must not be able to forget it.
// Apply with: node --env-file=.env scripts/migrate.mjs
await cp('supabase/migrations','dist/migrations',{recursive:true});
const webAssets=(await readdir('public/assets')).filter(f=>f.endsWith('.webp'));
async function optimizeReferences(dir){
 for(const entry of await readdir(dir,{withFileTypes:true})){
  const target=dir+'/'+entry.name;
  if(entry.isDirectory())await optimizeReferences(target);
  else if(/\.(html|js|mjs|css)$/.test(entry.name)){
   let text=await readFile(target,'utf8');
   for(const name of webAssets)text=text.replaceAll('/assets/'+name.replace(/\.webp$/,'.png'),'/assets/'+name);
   await writeFile(target,text);
  }
 }
}
await optimizeReferences('dist/client');await optimizeReferences('dist/server');
// SEO pass over the built pages. Canonicals are rewritten from SITE_ORIGIN so
// the committed HTML never pins the site to whichever host it was built on, and
// account pages are marked noindex: they hold nothing worth ranking and would
// otherwise dilute the storefront's relevance.
{
 const {siteOrigin,metaTags,jsonLd,organisation,website}=await import('../server/seo.mjs');
 const origin=siteOrigin(process.env);
 const pages={
  'dist/client/index.html':{path:'/',title:'LYVERNE — Everyday, elevated.',image:'/assets/tee-front.png',
   description:'Lyverne. Everyday, elevated. A Bangladeshi clothing label making relaxed, considered pieces — the signature tee and four original graphic designs.',
   schema:o=>[organisation(o),website(o)]},
  'dist/client/studio/index.html':{path:'/studio/',title:'Style Studio — LYVERNE',image:'/assets/studio-hero.png',
   description:'The Lyverne Style Studio. Find your colours, build a look, and discover the small things that make it yours.',schema:()=>[]},
 };
 const noindex=['login','signup','dashboard','admin'];
 for(const [file,page] of Object.entries(pages)){
  let html;try{html=await readFile(file,'utf8');}catch{continue;}
  html=html.replace(/<link rel="canonical"[^>]*>/g,'').replace(/<meta name="description"[^>]*>/g,'');
  const head=metaTags({origin,path:page.path,title:page.title,description:page.description,image:page.image})
   +page.schema(origin).map(jsonLd).join('');
  await writeFile(file,html.replace('</head>',head+'</head>'));
 }
 for(const name of noindex){
  const file=`dist/client/${name}/index.html`;
  let html;try{html=await readFile(file,'utf8');}catch{continue;}
  if(!html.includes('name="robots"'))await writeFile(file,html.replace('</head>','<meta name="robots" content="noindex, nofollow"></head>'));
 }
}
for(const name of webAssets)await rm('dist/client/assets/'+name.replace(/\.webp$/,'.png'),{force:true});
// optimizeReferences rewrites .png to .webp inside built files, but product
// image paths live in the database, which it cannot reach. Without this list
// every DB-stored /assets/*.png would 404 in dist, taking the product photo,
// the social card and the structured-data image with it. Emit the converted
// names so the server can normalise those paths at render time.
await writeFile('server/web-assets.js',`// Generated by scripts/build.mjs. Do not edit.\n// Basenames available as .webp in the build output.\nexport const webAssets=new Set(${JSON.stringify(webAssets.map(n=>n.replace(/\.webp$/,'')))});\n`);
console.log('Build complete. All referenced assets are present. Worker and storefront output: dist/');
