import {siteNav} from '../server/shell.js';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {products,signatureProducts} from '../public/catalog.js';
import {occasions,moods,weatherOptions} from '../public/style-guide.js';
const options=values=>Object.entries(values).map(([value,label])=>`<option value="${value}">${label}</option>`).join('');
export async function renderStudio(){
 const home=await readFile('public/index.html','utf8');
 const accountMenu=home.slice(home.indexOf('<!-- account:start -->'),home.indexOf('<!-- account:end -->')+'<!-- account:end -->'.length);
 const shared=home.slice(home.indexOf('<svg class="filter-defs"'),home.indexOf('<a class="skip-link"'));
 const dialogs=home.slice(home.indexOf('<dialog id="menu-dialog"'),home.indexOf('</body>')).replaceAll('href="#home"','href="/"').replaceAll('href="#story"','href="/#story"').replaceAll('href="#details"','href="/#details"');
 const footer=home.slice(home.indexOf('<footer id="contact"'),home.indexOf('<dialog id="menu-dialog"')).replaceAll('href="#home"','href="/"').replaceAll('href="#story"','href="/#story"').replaceAll('href="#signature"','href="/#signature"').replaceAll('href="#find-your-color"','href="/#find-your-color"').replace(/<!-- home-game:start -->[\s\S]*?<!-- home-game:end -->/g,'').replace(' data-footer-game','');
 const html=`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#F3EEE4"><title>Style Studio — LYVERNE</title><meta name="description" content="A little inspiration. A little more you. Explore Lyverne’s guided outfit assistant, color playground, daily notes and saved style ideas."><link rel="canonical" href="https://lyverne.yusuf-pay.chatgpt.site/studio/"><link rel="icon" href="/assets/lyverne-monogram.png"><link rel="preload" href="/assets/khand-bold.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/transitions.css"><link rel="stylesheet" href="/home.css"><link rel="stylesheet" href="/site-nav.css"><link rel="stylesheet" href="/studio.css"><script>if(!matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.classList.add('is-loading');setTimeout(()=>{document.documentElement.classList.remove('is-loading');document.documentElement.classList.add('page-ready')},2500)}</script><script type="module" src="/transitions.js"></script><script type="module" src="/app.js"></script><script type="module" src="/studio.js"></script><script type="module" src="/films.js"></script><link rel="stylesheet" href="/account-menu.css"><script type="module" src="/account-menu.js"></script></head><body class="studio-page">${shared}
 <a class="skip-link" href="#main">Skip to style studio</a>
 ${siteNav}
 <main id="main">
 <section class="studio-hero" aria-labelledby="studio-title"><div class="studio-hero-copy"><p class="eyebrow">THE LYVERNE STYLE STUDIO / VOL. 01</p><h1 id="studio-title">GOOD STYLE.<br>A LITTLE<br><span class="circled-word">MORE YOU.<svg class="draw-circle" viewBox="0 0 530 135" preserveAspectRatio="none" aria-hidden="true"><path pathLength="1" d="M312 121C100 143-10 98 12 51 32 3 255-6 422 13 568 32 541 116 291 123L112 131"/></svg></span></h1><p class="studio-intro">A fresh perspective on your everyday.<br>Find your colors, build a look, and discover<br>the little things that make it yours.</p><a class="oval-link" href="#assistant">Find my next look <span>↗︎</span></a><span class="studio-hero-note hand-note">No rules. Just a little direction.<svg class="draw-arrow" viewBox="0 0 130 100" aria-hidden="true"><path pathLength="1" d="M120 12C26-10 7 52 73 80m-15-19 18 21-27 3"/></svg></span></div>
 <div class="studio-visual"><figure class="editorial-frame"><img data-eager-image src="/assets/studio-editorial.png" alt="Lyverne black drop-shoulder tee styled with warm cream trousers in a sunlit studio" width="1086" height="1448" fetchpriority="high"><figcaption>THE EVERYDAY UNIFORM, RECONSIDERED. <span>01 / LYVERNE</span></figcaption></figure><div class="studio-sticker" aria-hidden="true"><svg viewBox="0 0 180 180"><defs><path id="studio-seal" d="M90 90m-68 0a68 68 0 1 1 136 0a68 68 0 1 1-136 0"/></defs><text><textPath href="#studio-seal" textLength="420">A LITTLE LESS NOISE · A LITTLE MORE YOU · </textPath></text></svg><span>BE<br>YOU.</span></div><div class="visual-swatch" aria-hidden="true"><i></i><i></i><i></i><span>LESS, BUT BETTER.</span></div></div>
 </section>
 <section class="daily-note" aria-labelledby="quote-title"><div class="daily-label"><span class="tiny-star" aria-hidden="true">✳</span><p class="eyebrow" id="quote-title">A NOTE FOR TODAY</p><time id="quote-date"></time></div><blockquote><p id="daily-quote">A quiet detail can say everything.</p><cite>— THE LYVERNE NOTEBOOK</cite></blockquote><div class="daily-action"><span class="eyebrow">TRY THIS TODAY</span><p id="daily-challenge">Choose a single accent. Let everything else breathe.</p><button id="challenge-toggle" aria-pressed="false">I’LL TRY IT <span>↗︎</span></button></div></section>
 <section class="studio-assistant" id="assistant" aria-labelledby="assistant-title"><div class="studio-section-head"><div><p class="eyebrow">01 / A LITTLE DIRECTION</p><h2 id="assistant-title">LET’S FIND<br>YOUR <em>EVERYDAY.</em></h2></div><p>Your day. Your mood. Your kind of fit.<br>Start with a few details. We’ll bring the ideas.</p></div>
 <div class="assistant-layout"><form class="style-form" id="style-form"><div class="assistant-label"><img src="/assets/lyverne-monogram.png" alt="" width="36" height="36"><div><strong>YOUR STYLE COMPANION</strong><span>Guided preview · live AI coming later</span></div><span class="companion-dot" aria-hidden="true"></span></div><h3>What does your day look like?</h3><p class="form-help">Start here. There’s no wrong answer.</p><div class="style-fields"><label>THE OCCASION<select name="occasion" id="style-occasion">${options(occasions)}</select></label><label>THE FEELING<select name="mood" id="style-mood">${options(moods)}</select></label><label>THE WEATHER<select name="weather" id="style-weather">${options(weatherOptions)}</select></label><label>YOUR STARTING PIECE<select name="color" id="style-color">${products.map(p=>`<option value="${p.id}">${p.id.startsWith('graphic-')?p.name:p.color+' tee'}</option>`).join('')}</select></label></div><label class="prompt-label" for="style-prompt">A LITTLE MORE ABOUT YOUR LOOK <span>OPTIONAL</span></label><textarea id="style-prompt" name="prompt" maxlength="500" rows="3" placeholder="Try: a minimal black tee outfit for a warm weekend…" aria-describedby="prompt-hint"></textarea><p class="prompt-hint" id="prompt-hint">This local guide recognizes color, occasion, weather and fit cues. Your words stay in this browser.</p><div class="prompt-chips" role="group" aria-label="Try a styling prompt"><button type="button" data-prompt="A smart black tee outfit for dinner">Dinner plans ↗︎</button><button type="button" data-prompt="A relaxed street outfit with orange for a warm weekend">A little color ↗︎</button><button type="button" data-prompt="A minimal cream tee outfit for a cool workday on a budget">Use what I own ↗︎</button></div><button type="submit" class="build-look">BUILD MY LOOK <span>↗︎</span></button><p class="form-footnote">A starting point, never a dress code.</p></form>
 <div class="look-result" id="look-result" tabindex="-1" aria-labelledby="look-title"><div class="look-topline"><span class="eyebrow">YOUR STYLE NOTE / <span id="look-number">01</span></span><span id="look-context">EVERYDAY · QUIET MINIMAL</span></div><p id="guide-message" class="guide-message" role="status"></p><div class="look-visual-row"><div class="look-tee"><img id="look-image" src="/assets/tee-front.png" alt="Onyx Black Lyverne tee" width="1254" height="1254"><span>START WITH ONE GOOD PIECE.</span></div><div class="look-identity"><h3 id="look-title">QUIETLY<br>PUT TOGETHER.</h3><div id="look-palette" class="look-palette"></div></div></div><dl id="look-items" class="look-items"></dl><div class="look-reason"><h4>WHY IT WORKS</h4><p id="look-why"></p></div><div class="look-advice"><details><summary>The fit & final layer <span>+</span></summary><p id="look-fit"></p><p id="look-layer"></p></details><p id="look-extra" hidden></p></div><div class="look-actions"><button id="save-look" class="oval-link">Save this look <span>＋</span></button><button id="look-product" class="piece-link" data-product-id="signature-onyx">See the tee ↗︎</button></div><div class="followup-chips" role="group" aria-label="Adjust this look"><span>MAKE IT…</span><button data-refine="smart">A little smarter</button><button data-refine="street">More relaxed</button><button data-refine="warm">Warm-weather ready</button></div></div></div></section>
 <section class="color-playground" id="color-playground" aria-labelledby="color-title" data-nav-theme="dark"><div class="scallop-edge" aria-hidden="true"><svg viewBox="0 0 1200 120" preserveAspectRatio="none"><path d="M0 120V100a100 100 0 0 1 200 0 100 100 0 0 1 200 0 100 100 0 0 1 200 0 100 100 0 0 1 200 0 100 100 0 0 1 200 0 100 100 0 0 1 200 0v20Z"/></svg></div><div class="studio-section-head"><div><p class="eyebrow">02 / PLAY A LITTLE</p><h2 id="color-title">FIND YOUR<br><em>COLOR STORY.</em></h2></div><p>One signature. Four starting points.<br>Tap a color. See what goes with it.</p><svg class="spinning-sun" viewBox="0 0 120 120" aria-hidden="true"><use href="#sun-doodle"/></svg></div><div class="color-lab"><div class="color-stage"><div class="color-disc" aria-hidden="true"></div><img id="color-tee" src="/assets/tee-front.png" alt="Onyx Black Lyverne tee" width="1254" height="1254" loading="lazy"><span class="color-stage-caption">THE SIGNATURE TEE / FOUR WAYS TO BE YOU</span></div><div class="color-controls"><div class="color-buttons" role="group" aria-label="Choose your tee color">${signatureProducts.map((p,i)=>`<button aria-label="Style ${p.color}" aria-pressed="${i===0}" data-color="${p.id}" style="--swatch:${p.swatch}"><i></i><span>${p.color}</span></button>`).join('')}</div><h3 id="color-story-title">ONYX, MEET STONE.</h3><p id="color-story-copy">Start dark. Add a little warmth. A soft neutral makes the black tee feel effortless.</p><div class="palette-bars" id="palette-bars"></div><button class="oval-link" id="use-palette">Build with this color <span>↗︎</span></button><span class="color-tip">STYLE NOTE: LET ONE COLOR LEAD.</span></div></div></section>
 <section class="style-school" aria-labelledby="school-title"><div class="studio-section-head"><div><p class="eyebrow">03 / SMALL THINGS, BIG DIFFERENCE</p><h2 id="school-title">A BETTER EYE.<br>ONE DETAIL AT A TIME.</h2></div><p>Three ideas to keep in your back pocket.<br>Tap a card to try something different.</p></div><div class="lesson-grid"><details class="lesson"><summary><span class="lesson-index">01 / PROPORTION <span>＋</span></span><div class="proportion-art" aria-hidden="true"><img src="/assets/tee-front.png" alt="" loading="lazy"><div class="trouser-art"></div></div><h3>GIVE IT<br>SOME ROOM.</h3><span class="lesson-hint">OPEN THE STYLE NOTE ↗︎</span></summary><p>A dropped shoulder already brings volume. Pair it with a straight trouser and a clean hem. For more shape, try a small front tuck before changing the whole outfit.</p><button data-lesson="street">Try a relaxed silhouette ↗︎</button></details><details class="lesson"><summary><span class="lesson-index">02 / COLOR <span>＋</span></span><div class="contrast-art" aria-hidden="true"><i></i><i></i><i></i></div><h3>ONE ACCENT.<br>ENOUGH SAID.</h3><span class="lesson-hint">OPEN THE STYLE NOTE ↗︎</span></summary><p>Give one color the lead. Orange feels considered alongside black, charcoal or warm cream. Repeat a quiet neutral in your shoes to connect the outfit.</p><button data-lesson="color">Play with orange ↗︎</button></details><details class="lesson"><summary><span class="lesson-index">03 / DETAIL <span>＋</span></span><div class="detail-art" aria-hidden="true"><img src="/assets/tee-detail.png" alt="" loading="lazy"></div><h3>LET THE LITTLE<br>THINGS SPEAK.</h3><span class="lesson-hint">OPEN THE STYLE NOTE ↗︎</span></summary><p>A clean neckline, a sleeve that sits naturally, one small accessory. Notice these before adding another layer. Texture and fit can do the work of a loud graphic.</p><button data-lesson="minimal">Build a quiet look ↗︎</button></details></div></section>
 <section class="studio-film" aria-labelledby="studio-film-title"><div class="studio-section-head"><div><p class="eyebrow">THE MOTION NOTEBOOK</p><h2 id="studio-film-title">SEE THE<br><em>WHOLE FEELING.</em></h2></div><p>Shape, texture, a quiet signature.<br>A silent 18-second motion lookbook.</p></div><div class="film-player"><video controls playsinline preload="none" poster="/assets/studio-editorial.png" aria-label="Lyverne Signature Tee motion lookbook"><source src="/assets/lyverne-signature-film.mp4" type="video/mp4"></video><button class="film-play" aria-label="Play Signature Tee film"><span>▷</span> PLAY FILM</button></div></section>
 <section class="saved-notes" id="saved-notes" aria-labelledby="saved-title"><div class="saved-heading"><div><p class="eyebrow">04 / KEEP THE GOOD ONES</p><h2 id="saved-title">YOUR STYLE<br><em>NOTEBOOK.</em></h2></div><p>Ideas for the days you don’t want to overthink it.<br>Saved on this device, just for you.</p><span class="saved-counter"><span id="saved-count">00</span> / 12</span></div><div id="saved-grid" class="saved-grid"></div><p id="notebook-status" role="status"></p><div class="studio-bottom-note"><span>STAY CURIOUS. STAY YOU.</span><button class="motion-toggle" aria-pressed="false" aria-label="Pause product motion"><span>Ⅱ</span> PAUSE MOTION</button><a href="#main">BACK TO TOP ↑</a></div></section>
 </main>${footer}${dialogs}</body></html>`;
 await mkdir('public/studio',{recursive:true});await writeFile('public/studio/index.html',html);
}
